services:
  desktop:
    image: ledanghuy/workspace:desktop-micro
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      PUID: 0
      PGID: 0
      START_DOCKER: false
      PASSWORD: ${PASSWORD}
      FM_HOME: /workspace
      GIT_USER: workspace
      GIT_EMAIL: workspace@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - /mnt:/mnt
      - /mnt/workspace:/workspace
      - /config:/docker_home
      - /:/hostmachine
    network_mode: host
    shm_size: 4gb
    restart: always
