services:
  desktop:
    image: ledanghuy/workspace:desktop-micro
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      PUID: 0
      PGID: 0
      START_DOCKER: false
      PASSWORD: ${PASSWORD}
      FM_HOME: ${FM_HOME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - /mnt:/mnt
      - /:/hostmachine
      - ${FM_HOME}:${FM_HOME}
    network_mode: host
    shm_size: 4gb
    restart: always

  serveo:
    image: docker:latest
    restart: always
    working_dir: ${PWD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:${PWD}
    entrypoint: docker compose exec desktop bash -c "autossh -M 0 -R 80:localhost:3000 serveo.net"
